// The big book of table talk, part three: more of what the regulars say most often.
// Merged into LINES / PERSONA_LINES by botlines.js. Same placeholders as the other books.

export const EXTRA_LINES = {
  greet: [
    "Cards are dealt. Let's see what kind of liars we're working with.", "Everybody breathe normal. Normal, I said.", "One of you is already sweating. I can hear it.",
    "Good luck, and I mean that for most of you.", "Somebody here is smiling on the inside.", "Remember, folks: it's only a game. Until it isn't.",
    "Let's keep it civil. For about five minutes.", "May the cards be kind. They won't be, but may they.",
  ],
  firstDay: [
    "Nobody died by accident last night. Let's think about who wanted it.", "Everybody tell me where your head's at. One sentence each.",
    "I don't trust anybody yet. That's the healthy way to start.", "Talk. The Jokers can't hide forever if we keep them talking.",
    "Somebody at this table slept real well last night. I want to know who.", "Let's not rush this. Rushed votes hang honest folk.",
    "The first vote is always a coin toss. Let's make it a weighted coin.", "If you've got a hunch, say it now. Hunches get better with company.",
  ],
  accuse: [
    "Hate to say it, but {x}. {reason}", "Let's hear from {x}, because {reason}", "Here's a thought: {x}. {reason}", "Everybody look at {x} for a second. {reason}",
    "I'm going to put {x} on the spot. {reason}", "{x}, I've got my doubts about you. {reason}", "Something doesn't add up with {x}. {reason}",
    "If I'm picking one name, it's {x}. {reason}", "My eye keeps drifting to {x}. {reason}", "{x} is the one I'd check first. {reason}",
    "Call me crazy, but {x}. {reason}", "Nobody's said it, so I will: {x}. {reason}", "I've watched {x} long enough. {reason}", "{x} is making my nose itch. {reason}",
    "Put a pin in {x}. {reason}", "I'm not married to it, but {x}. {reason}", "Take a hard look at {x}. {reason}", "Can't prove it yet, but {x}. {reason}",
  ],
  accuseStrong: [
    "I'd bet the house on {x}. {reason}", "It's {x}, and I'll hang my hat on it. {reason}", "Stop dancing around it. {x} is our Joker. {reason}",
    "Every road leads back to {x}. {reason}", "{x}, the jig is up. {reason}", "Vote {x}. I'm sure. {reason}",
  ],
  r_gut: [
    "{x} answers too fast, like it was rehearsed.", "{x} keeps checking everybody's faces.", "{x}'s been too helpful. Nobody's that helpful.",
    "{x} hasn't taken one risk all game.", "{x} is the only one who looks relaxed.", "{x} laughed when the body was found.", "{x} is steering. I don't like being steered.",
    "{x} keeps agreeing with whoever talked last.", "{x} changes the subject every time it gets warm.", "There's something rehearsed about {x}.",
    "{x} sat up straight when the Jokers came up.", "{x} hasn't looked me in the eye all night.", "{x} flinched. Tiny, but I saw it.",
  ],
  r_quiet: [
    "{x} has been awfully careful not to say anything.", "{x} is sitting this one out, and I don't like it.", "Quiet as a church mouse, that {x}. Church mice bite.",
  ],
  agree: [
    "{y} isn't wrong. {x} is off.", "I'm leaning where {y} is leaning. {x}.", "{y}, I see it too. {x} has been slippery.", "Same page as {y}. {x}.",
    "Put me with {y}. {x} has some explaining to do.", "{y}'s read on {x} matches mine.", "I didn't want to say it, but {y} is right. {x}.",
    "{y} called it. {x} is shady.", "Seconding {y}. {x}.", "That's the smartest thing anybody's said tonight, {y}. {x}.",
  ],
  disagree: [
    "I'm not there yet on {x}, {y}.", "Slow down, {y}. You've got nothing on {x} but a feeling.", "{x}? I'd look anywhere else first, {y}.",
    "You're chasing the wrong rabbit, {y}.", "That's a thin case against {x}, {y}.", "{y}, you want {x} gone awful bad. Why?",
    "Not buying it, {y}. {x} has played it straight.", "{y}, I'll need more than that before I hang {x}.",
  ],
  defendSelf: [
    "I've got nothing to hide, and a {card} to prove it.", "You're way off. I'm a {card} and I've been trying to help.", "Point that somewhere useful, {x}.",
    "If I were a Joker, I'd be a lot quieter than this.", "I've been on the town's side since the cards came out.", "Wrong tree, {x}. There's a Joker laughing at you right now.",
    "Check my votes. Clean as a whistle.", "Me? I'd sooner eat my hat.", "That's a waste of a day, {x}. I'm a {card}.",
  ],
  defendSelfMafia: [
    "Save it, {x}. I've been clean all night.", "You'll feel real silly when the truth comes out, {x}.", "I've been hunting Jokers since the deal. Ask anybody.",
    "Sure, blame the one who's been helping.", "I'm a {card}. Go bark at someone else.", "Take it easy, {x}. Wrong suspect, wrong day.",
    "Hang me and the real Jokers walk out laughing.", "I get it. Somebody has to be the suspect. It isn't me.",
  ],
  counterAccuse: [
    "Pretty rich coming from you, {x}.", "You're first in line to blame me, {x}. Funny, that.", "I'd look at whoever's pushing hardest. That's you, {x}.",
    "Nice deflection, {x}. Who are you protecting?", "Keep it up, {x}. You're painting yourself into a corner.", "{x}, you've been looking for a scapegoat all day.",
  ],
  defendOther: [
    "Easy, now. {x} has been with us the whole way.", "I'll stand up for {x}. Look elsewhere.", "{x} has been nothing but straight. Let it go.",
    "{x}? No. I'd trust {x} with my wallet.", "Hanging {x} would be a gift to the Jokers.",
  ],
  question: [
    "{x}, what's your gut telling you?", "Who's been too quiet? Anybody keeping track?", "{x}, who'd you vote for if the vote opened right now?",
    "Somebody walk me through last night. Who looked shifty?", "{x}, you're making a face. What is it?", "Anybody changed their mind since this morning?",
    "{x}, who do you trust at this table?", "What's the play here, people?",
  ],
  humanQuiet: [
    "{h}, you've been awfully quiet over there. What's your read?", "{h}, we could use your eyes on this. Who?", "Let's hear from {h}. Anybody bothering you?",
    "{h}, don't be shy. Who's lying?", "{h}, you've been watching. Who looks wrong to you?", "{h}? Your two cents, please.",
    "I want {h}'s take before this goes any further.", "{h}, silence isn't a vote. Talk to us.",
  ],
  answerWho: [
    "I keep circling back to {x}. {reason}", "{x}. Not sure, but {x}.", "Honestly? {x}. {reason}", "Right this second, {x}.", "If you're asking me: {x}. {reason}",
    "{x} is top of my list.", "I'd put money on {x}.",
  ],
  answerNone: [
    "Too early to call.", "Nobody's shown their hand yet.", "Give me another round of talk.", "I've got suspicions, but nothing I'd hang anyone on.",
    "Everybody looks guilty to me right now.", "I'm keeping my cards close for now.", "Let the quiet ones talk first.",
  ],
  answerTrust: ["{x}'s been solid.", "I'd trust {x} before most of this table.", "{x} isn't my worry.", "Leave {x} be. {x} is fine."],
  answerDistrust: ["{x}? I've got my eye on {x}.", "Wouldn't trust {x} to hold my coat.", "{x}'s story has holes.", "Keep watching {x}."],
  banter: [
    "Somebody's playing the saxophone next door. Badly.", "This table's seen more lies than a courthouse.", "My coffee went cold an hour ago. Figures.",
    "If walls could talk, these ones would plead the fifth.", "Anybody else hungry? Murder makes me hungry.", "The streetlight outside keeps flickering. Creepy.",
    "I bet the bartender knows everything and says nothing.", "You can smell the rain through the floorboards.", "Nobody sit with their back to the door.",
    "My lucky rabbit's foot isn't feeling lucky.", "Whoever brought the cheap cigars: never again.", "I used to play this game for fun.",
    "The radio said a storm's rolling in. Fitting.", "Pass the peanuts. And the alibis.",
  ],
  deathReact: [
    "We lost {x}. That one hurts.", "They got {x} in their sleep. Cowards.", "{x}. Of all people.", "Somebody here is going to answer for {x}.",
    "Poor {x}. Never saw it coming.", "{x} was one of the good ones.", "Another empty chair. {x}'s.", "{x}'s coffee is still warm.",
  ],
  savedReact: ["Everybody's still here. That's a miracle.", "The Jokers missed. Good.", "Somebody had a guardian tonight.", "Nobody's dead. I'll drink to that."],
  quietReact: ["Quiet night. Suspicious night.", "Nobody died. Don't get comfortable.", "The Jokers took a breath. So should we."],
  voteFor: ["{x}, sorry. My vote's on you.", "Going with {x}.", "It's {x}. Final answer.", "{x}. I hope I'm right.", "My chip goes on {x}.", "{x}, you had it coming."],
  voteSkip: ["Skipping. Not hanging anyone blind.", "I'm out on this one. Skip.", "Skip. We'll know more tomorrow."],
  readyVote: ["I've heard enough.", "Let's vote.", "Ready.", "Time to decide.", "Let's put it to the table."],
  pressure: ["We need a name, folks.", "Clock's running. Pick.", "Talk's cheap. Votes aren't.", "Somebody commit to something."],
  replyGreet: ["Evening, {h}. Pull up.", "Hey, {h}. Good to see you breathing.", "{h}! About time.", "Hi, {h}. Mind the smoke."],
  replyThanks: ["Sure thing, {h}.", "Don't mention it.", "Anytime, pal."],
  replyInsult: ["Real mature, {h}.", "Temper, {h}. It's showing.", "I'll remember that at the vote, {h}.", "Watch it, {h}."],
  replyLaugh: ["Ha. Glad you're having fun, {h}.", "Laugh while you can.", "Heh. Okay."],
  replyAskMe: ["What is it, {h}?", "I'm listening, {h}.", "Yeah, {h}? Spit it out."],
  replyAccusedByHuman: ["Me, {h}? Take a closer look.", "You're barking up the wrong tree, {h}.", "Big mistake, {h}. I'm on your side.", "{h}, I've been helping all game."],
  replyVoteOtherAgree: ["You and me both, {h}. {x}.", "{x}, yeah. Good eye, {h}.", "I was thinking {x} too, {h}."],
  replyVoteOtherDisagree: ["{x}? I don't see it, {h}.", "Not {x}, {h}. Look elsewhere.", "{h}, {x} has been straight all game."],
  replyVoteOther: ["{x}? Could be, {h}.", "Maybe, {h}. What's your reason?", "{x}. Hm. Keep talking, {h}."],
  replyPleaBelieve: ["Alright, {h}. I'll take your word.", "Okay, {h}. You're off my list. For now."],
  replyPleaDoubt: ["Sure, {h}. That's what they all say.", "Prove it at the vote, {h}.", "Hmm. Not convinced, {h}."],
  mafiaChat: ["Nice and easy. They suspect each other.", "Tomorrow, point at the loudest one.", "Keep your face straight. We're winning.", "If it gets hot, I'll start a fight to distract them."],
  mafiaSuggest: ["{x}. They've been too sharp today.", "I say {x}. Clean and quiet.", "{x} is trouble. Let's end it tonight.", "Tonight's the night for {x}."],
  mafiaFollow: ["{x}. Consider it done.", "Agreed, {x}.", "{x} it is. Goodnight, {x}."],
  execMafia: ["Got one! Keep going.", "A Joker! About time.", "One down. Don't stop now."],
  execTown: ["That was an innocent {card}. We've got a problem.", "We hanged our own. Great.", "A {card}. Somebody led us wrong."],
  lastTown: ["You'll see. I'm a {card}. Find the real ones.", "I was on your side. Remember who pushed this.", "Tonight you'll know I was right."],
  lastMafia: ["You got me fair and square. Well, mostly.", "Heh. One down, but the night is young.", "Enjoy it. My partner won't make it easy."],
  winTown: ["We did it! The Jokers are done.", "Justice, served cold.", "The town wins. Drinks on the house!"],
  winMafia: ["This town is ours.", "Nobody saw a thing.", "Pleasure doing business."],
  loseTown: ["They fooled us. Good game.", "Next time, I'm trusting my gut.", "Well played, Jokers."],
  loseMafia: ["You got us. Good game.", "Next time.", "Well played, town."],
  ghostChat: ["Look at them squabble. Adorable.", "I can see the Jokers from here. Oh, this is painful.", "Can ghosts drink? Asking for me."],
  replyQuietMe: [
    "I talk when I've got something worth saying, {h}.", "Quiet isn't guilty, {h}. I've been listening.", "Fine, {h}. You want words? Here come words.",
    "I've been watching, {h}. Watching's how you catch them.", "Some of us think before we talk, {h}.", "Alright, alright. I'll speak up.",
    "I was saving my breath, {h}. Not anymore.", "You noticed, huh? Fair enough, {h}.",
  ],
  answerDead: ["{x}? {x}'s gone, {h}. Let's worry about the living.", "{x} can't help us now, {h}.", "Leave {x} out of it, {h}. {x} is in the ground."],
  answerDeadVictim: [
    "{x} was killed in the night, {h}. The Jokers don't kill their own, so {x} was one of us.", "The Jokers took {x}, {h}. That makes {x} innocent in my book.",
    "{x}? Murdered at night, {h}. Clean as they come.", "{x} was a victim, {h}, not a suspect. Look at who's still breathing.",
  ],
  r_accusedVictim: [
    "{x} was hounding {y}, and the Jokers killed {y}. {y} was innocent.", "{x} wanted {y} hanged. The Jokers got {y} first, so {y} was one of us.",
    "Remember who went after {y}? {x}. And {y} was clean.", "{x} pushed hard on {y}. {y} turned up dead and innocent.",
  ],
  execUnknown: [
    "Done. I hope we got the right one.", "We won't see that card until it's all over. Pray we're right.", "One less liar. Or one less friend. Time will tell.",
    "If the killing stops, we got a Joker.", "Tonight will tell us if we were right.", "That's done. Nobody gloat until the sun comes up.",
    "Face down, forever. Great. Now we wait.", "I'll sleep with one eye open, just in case we got it wrong.",
  ],
  ghostReply: ["Welcome, {h}. The view's better up here.", "Hey {h}. Want to watch them squirm?", "{h}! Come watch the living fumble."],
};

// more of each voice
export const EXTRA_PERSONA = {
  tough: {
    accuse: ["{x}, I don't like your face and I like your story less. {reason}", "Straight talk: {x}. {reason}"],
    agree: ["{y}'s right. {x} is dirty. I can smell it."],
    replyGreet: ["{h}. Sit down, keep your hands visible."],
    question: ["{x}. Talk. Now."],
    readyVote: ["Enough yapping. Vote."],
  },
  sharp: {
    accuse: ["Let's go over the numbers on {x}. {reason}", "{x}'s votes don't line up with {x}'s words. {reason}"],
    answerNone: ["The numbers aren't in yet.", "Not enough entries in the ledger."],
    banter: ["I count every chip on this table. Somebody's short."],
    readyVote: ["I have what I need. Vote."],
  },
  nervous: {
    accuse: ["Um, I don't want to cause trouble, but {x}? {reason}", "Oh gosh. {x}. Sorry. {reason}"],
    agree: ["Y-yeah, what {y} said! {x}!"],
    answerNone: ["I don't know! Nobody knows! That's the problem!"],
    readyVote: ["Can we vote before I faint?"],
  },
  dramatic: {
    accuse: ["{x}, the mask is slipping, darling. {reason}", "Behold, the villain of our little play: {x}. {reason}"],
    agree: ["Yes! {y} sees it! {x}!"],
    banter: ["If I die tonight, play something sad at the funeral."],
    readyVote: ["To the final act! Vote!"],
  },
  joker: {
    accuse: ["Odds-on favorite for Joker: {x}. {reason}", "Put it all on {x}. {reason}"],
    agree: ["I'll match {y}'s bet. {x}."],
    answerNone: ["The odds are even. Nobody's a favorite yet."],
    readyVote: ["Let's see the cards."],
  },
  grumpy: {
    accuse: ["{x}. Don't make me explain. Fine. {reason}", "It's {x}. Probably. Whatever. {reason}"],
    agree: ["Yeah. {y}'s right. {x}. Can we go?"],
    answerNone: ["Don't know. Don't care. Ask me later."],
    readyVote: ["Vote. Please. I want to go home."],
  },
  wise: {
    accuse: ["{x}, dear, I've seen that trick before. {reason}", "Listen to your elders: {x}. {reason}"],
    agree: ["{y} has sense. {x} it is, honey."],
    answerNone: ["Patience, dear. The liars always slip."],
    readyVote: ["Alright, children. Let's vote."],
  },
  rookie: {
    accuse: ["Is it {x}? It feels like {x}. {reason}", "Gee, {x} seems kinda suspicious? {reason}"],
    agree: ["Oh! Yeah, {y}! {x}!"],
    answerNone: ["I have no clue. Is that bad?"],
    readyVote: ["Is it voting time? I think I'm ready."],
  },
  hothead: {
    accuse: ["{x}! You! I've had it with you! {reason}", "It's {x}! Everybody wake up! {reason}"],
    agree: ["THANK you, {y}! {x}!"],
    answerNone: ["I don't know, and it's driving me nuts!"],
    readyVote: ["VOTE! Now!"],
  },
  charming: {
    accuse: ["{x}, darling, you're lovely, but {reason}", "I hate to do this to you, {x}. {reason}"],
    agree: ["Mm, {y} has good taste. {x}."],
    answerNone: ["I'm still deciding who to adore and who to hang, darling."],
    readyVote: ["Shall we, darlings?"],
  },
  analyst: {
    accuse: ["Weighing the evidence: {x}. {reason}", "The pattern implicates {x}. {reason}"],
    agree: ["{y}'s conclusion follows. {x}."],
    answerNone: ["The data is inconclusive."],
    readyVote: ["Sufficient data. Proceed to vote."],
  },
};
